### ISSUE TITLE
#crash dont write header on arsc < 23sdk

### ISSUE THREAD

**Issue by I1PABIJJA** [madisp/android-chunk-utils#2]
**Exception in thread "main" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:527)
	at java.nio.HeapByteBuffer.putInt(HeapByteBuffer.java:372)
	at pink.madis.apk.arsc.PackageChunk.writeHeader(PackageChunk.java:185)
	at pink.madis.apk.arsc.Chunk.writeHeader(Chunk.java:164)
	at pink.madis.apk.arsc.Chunk.toByteArray(Chunk.java:217)
	at pink.madis.apk.arsc.ChunkWithChunks.writePayload(ChunkWithChunks.java:68)
	at pink.madis.apk.arsc.Chunk.toByteArray(Chunk.java:221)
	at pink.madis.apk.arsc.ResourceFile.toByteArray(ResourceFile.java:70)
	at pink.madis.apk.arsc.ResourceFile.toByteArray(ResourceFile.java:63)**

++++++++
```
@Override
  protected void writeHeader(ByteBuffer output) {
    output.putInt(id);
    PackageUtils.writePackageName(output, packageName);
    output.putInt(0);  // typeStringsOffset. This value can't be computed here.
    output.putInt(lastPublicType);
    output.putInt(0);  // keyStringsOffset. This value can't be computed here.
    output.putInt(lastPublicKey);
    output.putInt(typeIdOffset); <===== crash
  }
```

but applications with version sdk >= 23 All written without errors
thanks.

**Comment by madisp** [comment]
Do you have a reproducing `.arsc`/`.apk` file?

**Comment by I1PABIJJA** [comment]
Yes, for example, I used a framework-res.apk application (resources.arsc) of miui firmware (4.4.2) and cyanogenmod13 (6.0.1). If need be, I can share a link to these two files.

**Comment by madisp** [comment]
No need, I've reproduced the issue, thanks for reporting this! Will take a look shortly.

**Comment by madisp** [comment]
Hi, version 0.0.7 with the fix should be available on jcenter now, can you give this a try?
